#ifndef VOY_RESPONSE_STATUS_H
#define	VOY_RESPONSE_STATUS_H

#include <glib.h>
// 1** Informational statuses
#define VOY_CONTINUE "Continue"
#define VOY_SWITCHING_PROTOCOLS "Switching Protocols"
#define VOY_PROCESSING "Processing"
// 2** Success statuses
#define VOY_OK "OK"
#define VOY_CREATED "Created"
#define VOY_ACCEPTED "Accepted"
#define VOY_NON_AUTHORITATIVE_INFORMATION "Non-Authoritative Information"
#define VOY_NO_CONTENT "No Content"
#define VOY_RESET_CONTENT "Reset Content"
#define VOY_PARTIAL_CONTENT "Partial Content"
#define VOY_MULTI_STATUS "Multi-Status"
#define VOY_ALREADY_REPORTED "Already Reported"
#define VOY_IM_USED "IM Used"
#define VOY_LOW_ON_STORAGE_SPACE "Low on Storage Space"
// 3** Redirection statuses
#define VOY_MULTIPLE_CHOICES "Multiple Choices"
#define VOY_MOVED_PERMANENTLY "Moved Permanently"
#define VOY_FOUND "Found"
#define VOY_SEE_OTHER "See Other"
#define VOY_NOT_MODIFIED "Not Modified"
#define VOY_USE_PROXY "Use Proxy"
#define VOY_SWITCH_PROXY "Switch Proxy"
#define VOY_TEMPORARY_REDIRECT "Temporary Redirect"
#define VOY_PERMANENT_REDIRECT "Permanent Redirect"
// 4** Client error statuses
#define VOY_BAD_REQUEST "Bad Request"
#define VOY_UNAUTHORIZED "Unauthorized"
#define VOY_PAYMENT_REQUIRED "Payment Required"
#define VOY_FORBIDDEN "Forbidden"
#define VOY_NOT_FOUND "Not Found"
#define VOY_METHOD_NOT_ALLOWED "Method Not Allowed"
#define VOY_NOT_ACCEPTABLE "Not Acceptable"
#define VOY_PROXY_AUTHENTICATION_REQUIRED "Proxy Authentication Required"
#define VOY_REQUEST_TIMEOUT "Request Timeout"
#define VOY_CONFLICT "Conflict"
#define VOY_GONE "Gone"
#define VOY_LENGTH_REQUIRED "Length Required"
#define VOY_PRECONDITION_FAILED "Precondition Failed"
#define VOY_REQUEST_ENTITY_TOO_LARGE "Request Entity Too Large"
#define VOY_REQUEST_URI_TOO_LONG "Request-URI Too Long"
#define VOY_UNSUPPORTED_MEDIA_TYPE "Unsupported Media Type"
#define VOY_REQUESTED_RANGE_NOT_SATISFIABLE "Requested Range Not Satisfiable"
#define VOY_EXPECTATION_FAILED "Expectation Failed"
#define VOY_IM_A_TEAPOT "I'm a teapot"
#define VOY_ENHANCE_YOUR_CALM "Enhance Your Calm"
#define VOY_UNPROCESSABLE_ENTITY "Unprocessable Entity"
#define VOY_LOCKED "Locked"
#define VOY_FAILED_DEPENDENCY "Failed Dependency"
#define VOY_UNORDERED_COLLECTION "Unordered Collection"
#define VOY_UPGRADE_REQUIRED "Upgrade Required"
#define VOY_PRECONDITION_REQUIRED "Precondition Required"
#define VOY_TOO_MENY_REQUESTS "Too Many Requests"
#define VOY_REQUSET_HEADER_FIELDS_TOO_LARGE "Request Header Fields Too Large"
#define VOY_NO_RESPONSE "No Response"
#define VOY_RETRY_WITH "Retry With"
#define VOY_BLOCKED_BY_WINDOWS_PARENTAL_CONTROLS "Blocked by Windows Parental Controls"
#define VOY_PARAMETER_NOT_UNDERSTOOD "Parameter Not Understood"
#define VOY_CONFERENCE_NOT_FOUND "Conference Not Found"
#define VOY_NOT_ENOUGH_BANDWIDTH "Not Enough Bandwidth"
#define VOY_SESSION_NOT_FOUND "Session Not Found"
#define VOY_METHOD_NOT_VALID_IN_THIS_STATE "Method Not Valid in This State"
#define VOY_HEADER_FIELD_NOT_VALID_FOR_RESOURCE "Header Field Not Valid for Resource"
#define VOY_INVALID_RANGE "Invalid Range"
#define VOY_PARAMETER_IS_READ_ONLY "Parameter Is Read-Only"
#define VOY_AGGREGATE_OPERATION_NOT_ALLOWED "Aggregate Operation Not Allowed"
#define VOY_ONLY_AGGREGATE_OPERATION_ALLOWED "Only Aggregate Operation Allowed"
#define VOY_UNSUPPORTED_TRANSPORT "Unsupported Transport"
#define VOY_DESTINATION_UNREACHABLE "Destination Unreachable"
#define VOY_REQUEST_HEADER_TOO_LARGE "Request Header Too Large"
#define VOY_CERT_ERROR "Cert Error"
#define VOY_NO_CERT "No Cert"
#define VOY_HTTP_TO_HTTPS "HTTP to HTTPS"
#define VOY_CLIENT_CLOSED_REQUEST "Client Closed Request"
// 5** Server error statuses
#define VOY_INTERNAL_SERVER_ERROR "Internal Server Error"
#define VOY_NOT_IMPLEMENTED "Not Implemented"
#define VOY_BAD_GATEWAY "Bad Gateway"
#define VOY_SERVICE_UNAVAILABLE "Service Unavailable"
#define VOY_GATEWAY_TIMEOUT "Gateway Timeout"
#define VOY_HTTP_VERSION_NOT_SUPPORTED "HTTP Version Not Supported"
#define VOY_VARIANT_ALSO_NEGOTIATES "Variant Also Negotiates"
#define VOY_INSUFFICIENT_STORAGE "Insufficient Storage"
#define VOY_LOOP_DETECTED "Loop Detected"
#define VOY_BANDWIDTH_LIMIT_EXCEEDED "Bandwidth Limit Exceeded"
#define VOY_NOT_EXTENDED "Not Extended"
#define VOY_NETWORK_AUTHENTICATION_REQUIRED "Network Authentication Required"
#define VOY_OPTION_NOT_SUPPORTED "Option not supported"
#define VOY_NETWORK_READ_TIMEOUT_ERROR "Network read timeout error"
#define VOY_NETWORK_CONNECT_TIMEOUT_ERROR "Network connect timeout error"

extern gint voy_response_status_from_string(gchar const * string_status);
extern gchar *voy_repsonse_status_from_integer(gint integer_status);

#endif
